### ISSUE TITLE
degica___barcelona yb analysis

### ISSUE THREAD

**Issue by keheliya** [project-kotinos/issues#190]
Add a yb configuration file to https://github.com/project-kotinos/degica___barcelona.
Instuctions are here: https://github.com/project-kotinos/root/blob/master/README.md 
If you come across problems, add them as comments to this issue.

**Comment by keheliya** [comment]
Error:
```
/root/.yourbase/tools/rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
	from /root/.yourbase/tools/rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
	from /root/.yourbase/workspaces/c52ddf65534b/build/rubygems/bin/bundle:23:in `<main>'
```

**Comment by keheliya** [comment]
Error:
```
+ psql -c create database travis_ci_test; -U postgres
./yourbased.sh: 10: ./yourbased.sh: psql: not found
```

**Comment by keheliya** [comment]
works locally with side containers. Will work in CI once side containers make it to staging

**Comment by keheliya** [comment]
This is passing in staging now. Working config is at project-kotinos/degica___barcelona@52ed4b315fa62706e61967c2364ce4e20fe5e485
